# Generated by Django 2.2 on 2024-04-07 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0004_usernotes_userposts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserNotes',
            new_name='UserNote',
        ),
        migrations.RenameModel(
            old_name='UserPosts',
            new_name='UserPost',
        ),
    ]
