# Generated by Django 2.2 on 2024-04-18 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0005_auto_20240407_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='user',
            field=models.CharField(max_length=200),
        ),
    ]
