# Generated by Django 2.2 on 2024-04-21 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0008_profile_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_name',
        ),
    ]
