# Generated by Django 2.2 on 2024-04-21 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0009_remove_profile_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_name',
            field=models.CharField(default='test', max_length=100),
        ),
    ]
