# Generated by Django 2.2 on 2024-04-21 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0010_profile_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_name',
            new_name='username',
        ),
    ]
