# Generated by Django 2.2 on 2024-04-21 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0011_auto_20240421_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
